# Afficher les numéros d'inventaire associés aux pièces d'archive.
# Superflu : skos:prefLabel

PREFIX rico: <https://www.ica.org/standards/RiC/ontology#>
PREFIX vocab: <http://vocab.qdmtl.ca/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

SELECT ?record ?no_inv ?label
  WHERE {
    ?record a rico:Record ;
      rico:hasOrHadIdentifier ?id .
    ?id rico:hasIdentifierType vocab:inventoryNumber ;
      rico:textualValue ?no_inv .
    vocab:inventoryNumber skos:prefLabel ?label .
    FILTER(lang(?label)='fr')
  }

# Afficher les pièces d'archives associées à un numéro d'inventaire

PREFIX rico: <https://www.ica.org/standards/RiC/ontology#>
PREFIX vocab: <http://vocab.qdmtl.ca/>
SELECT ?record ?no_inv ?plan
  WHERE {
    ?record a rico:Record ;
      rico:hasOrHadIdentifier ?id ;
      rico:isRecordResourceAssociatedWithRecordResource ?plan .
    ?id rico:hasIdentifierType vocab:inventoryNumber ;
      rico:textualValue "11" .
    BIND ("11" AS ?no_inv) .
  }

# Afficher les pièces d'archives associées à un plan

PREFIX rico: <https://www.ica.org/standards/RiC/ontology#>
PREFIX vocab: <http://vocab.qdmtl.ca/>
SELECT ?plan ?record
  WHERE {
    ?record a rico:Record ;
      rico:isRecordResourceAssociatedWithRecordResource <http://data.qdmtl.ca/record/VM001-4-2_0806-1-1-P> .
    BIND ("data:record/VM001-4-2_0806-1-1-P" AS ?plan) .
  }

# Variante

PREFIX rico: <https://www.ica.org/standards/RiC/ontology#>
PREFIX vocab: <http://vocab.qdmtl.ca/>
SELECT ?record ?plan
  WHERE {
    ?record a rico:Record ;
      rico:hasContentOfType vocab:cartographicImage .
    ?plan rico:isRecordResourceAssociatedWithRecordResource ?record .
  }